# Generated by Django 4.2 on 2024-08-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('operator', 'Operator'), ('member', 'Member')], default=1, max_length=10, verbose_name='role'),
            preserve_default=False,
        ),
    ]
